import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = "zellij"

[window]
opacity = 0.6

[font]
normal = { family = "JetbrainsMono NF", style = "SemiBold" }
bold = { family = "JetbrainsMono NF", style = "Bold" }
italic = { family = "JetbrainsMono NF", style = "Italic" }
bold_italic = { family = "JetbrainsMono NF", style = "BoldItalic" }
size = 11.0

[env]
TERM = "xterm-256color"
